/* Full SEO content for dedicated programme pages — one crawlable URL each.
   Images are filenames resolved against /assets/site via window.asset(). */

const PROGRAM_CONTENT = {
  /* ============== VOCATIONAL ============== */

  "baking-confectionery": {
    slug: "baking-confectionery", category: "Vocational Training", icon: "cookie", image: "hero.png",
    seoTitle: "Baking & Confectionery Training for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "A hands-on baking and confectionery vocational programme for young adults with special needs in Chennai. Learn baking, decoration, packaging and safe kitchen skills that lead to real work and independence.",
    h1: "Baking & Confectionery Training for Special Needs",
    lede: "A supportive, hands-on baking programme in Chennai where young adults with intellectual and developmental disabilities learn real kitchen skills — building confidence, focus and a pathway to employment.",
    intro: "At Prisaum SEVA, our baking and confectionery training turns a warm, structured kitchen into a classroom. Trainees aged 12 and above learn to measure, mix, bake, decorate and package — at their own pace, with one-to-one guidance from trained instructors. Beyond the recipes, every session strengthens fine motor control, sequencing, hygiene and teamwork: the life skills that make independence possible.",
    age: "12 years and above", mode: "Vocational workshop · weekday programme", duration: "Ongoing, with individual skill milestones",
    learnHeading: "What trainees learn",
    learn: ["Safe kitchen practice — hygiene, handling equipment and following steps", "Measuring, mixing and baking breads, cookies, cakes and confectionery", "Icing, decoration and finishing techniques", "Packaging, labelling and presenting products for sale", "Working as a team and following a recipe from start to finish"],
    whoHeading: "Who this programme is for",
    who: "Young adults and children (12+) with intellectual disabilities, autism, Down syndrome, learning disabilities or slow learning abilities who benefit from practical, repetitive, confidence-building work in a calm environment.",
    outcomesHeading: "Outcomes & certification",
    outcomes: ["A recognised vocational skill that supports real employment", "Greater independence in daily living and routines", "Improved focus, coordination and self-confidence", "Pathway toward certification in handicrafts and food preparation"],
    faq: [
      { q: "What age can my child join the baking programme?", a: "Admissions are open to learners aged 12 and above. We assess each learner individually to tailor goals to their pace and needs." },
      { q: "Do trainees need prior experience?", a: "No prior experience is needed. We start from the basics — safety, measuring and simple recipes — and build up gradually with one-to-one support." },
      { q: "Is the programme residential?", a: "Prisaum SEVA offers both day and residential options across our two Chennai campuses, including a hostel at Manapakkam. Contact us to discuss what suits your family." },
      { q: "Does this lead to a certificate or employment?", a: "Yes. The programme builds toward certification in handicrafts and food preparation, and our career counselling team supports trainees and parents toward suitable work opportunities." },
    ],
    related: ["weaving", "eco-friendly-plate-making", "life-skills-training"],
  },

  "weaving": {
    slug: "weaving", category: "Vocational Training", icon: "grid-3x3", image: "whom-we-serve.png",
    seoTitle: "Weaving & Handloom Training for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "A calming handloom and weaving vocational programme for special needs young adults in Chennai. Build focus, fine motor skills and a marketable craft that supports independence and employment.",
    h1: "Weaving & Handloom Training for Special Needs",
    lede: "A calming, rhythmic handloom programme in Chennai where learners with special needs develop focus, fine motor control and a genuine craft they can be proud of.",
    intro: "Weaving is one of the most therapeutic vocational skills we teach. The steady rhythm of the handloom helps trainees with autism and intellectual disabilities regulate, concentrate and find flow. Step by step, learners progress from handling yarn to setting the loom and weaving finished pieces — developing patience, coordination and a marketable craft along the way, all under the guidance of skilled weavers and our support staff.",
    age: "12 years and above", mode: "Vocational workshop · weekday programme", duration: "Ongoing, with individual skill milestones",
    learnHeading: "What trainees learn",
    learn: ["Handling and preparing yarn and threads", "Setting up and operating a handloom safely", "Basic to intermediate weaving patterns and techniques", "Finishing, quality-checking and presenting woven products", "Concentration, sequencing and fine motor coordination"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) who respond well to calm, repetitive, sensory-friendly work — including those with autism, intellectual disabilities and slow learning abilities who benefit from a quiet, structured craft.",
    outcomesHeading: "Outcomes & certification",
    outcomes: ["A marketable handicraft skill and the focus to sustain it", "Noticeably improved fine motor control and attention", "A calming routine that supports self-regulation", "Pathway toward certification in handicrafts"],
    faq: [
      { q: "Is weaving suitable for a learner with autism?", a: "Yes — the calm, repetitive rhythm of the handloom is often especially well-suited to learners with autism, supporting focus and self-regulation." },
      { q: "What age can my child start?", a: "Weaving is open to learners aged 12 and above, with individual goals set after an initial assessment." },
      { q: "Are the woven products sold?", a: "Trainees learn to finish and present products to a sellable standard, which builds real-world skills and a sense of accomplishment." },
      { q: "How much one-to-one support is provided?", a: "Each learner works to a tailored plan with guidance from skilled weavers and our support staff, alongside small-group sessions for social skills." },
    ],
    related: ["baking-confectionery", "laundry-fabric-care", "occupational-therapy"],
  },

  "gardening-horticulture": {
    slug: "gardening-horticulture", category: "Vocational Training", icon: "sprout", image: "how-we-began.png",
    seoTitle: "Gardening & Horticulture Training for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "A hands-on, outdoor gardening and horticulture programme for special needs young adults in Chennai. Learn nursery work, crop care and landscaping while building independence and well-being.",
    h1: "Gardening & Horticulture Training for Special Needs",
    lede: "An outdoor, sensory-rich horticulture programme in Chennai where learners with special needs grow plants — and confidence — through nursery work, crop care and landscaping.",
    intro: "Working with soil, seeds and seasons is grounding and rewarding. Our gardening and horticulture training gives trainees aged 12 and above a productive routine in the open air: sowing, watering, potting, pruning and maintaining green spaces. The work builds physical coordination, responsibility and patience, while the calm of the garden supports emotional well-being — a genuinely therapeutic vocation.",
    age: "12 years and above", mode: "Vocational workshop · outdoor sessions", duration: "Ongoing, aligned to growing seasons",
    learnHeading: "What trainees learn",
    learn: ["Sowing, watering, potting and transplanting", "Nursery management and plant care routines", "Basic crop care, composting and soil preparation", "Landscape and green-space maintenance", "Responsibility, routine and working safely with tools"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) who thrive with active, outdoor, hands-on work — including those with autism, intellectual disabilities and slow learning abilities who benefit from routine and sensory engagement.",
    outcomesHeading: "Outcomes & certification",
    outcomes: ["A practical horticulture skill suited to real employment", "Improved physical coordination and stamina", "A calming, purposeful daily routine", "Pathway toward certification in gardening / horticulture"],
    faq: [
      { q: "Is the gardening programme suitable for sensory-sensitive learners?", a: "Yes — outdoor, hands-on horticulture is often calming and grounding. We tailor tasks and pacing to each learner's comfort and needs." },
      { q: "What will my child actually do?", a: "Trainees take part in real nursery and garden work — sowing, watering, potting, pruning and maintaining green spaces — with full supervision." },
      { q: "Does this lead to certification?", a: "Yes, the programme builds toward certification in gardening and horticulture, and our team guides next steps for employment." },
      { q: "Is it safe?", a: "All sessions are supervised, with tools and tasks matched to each learner's ability and clear safety routines." },
    ],
    related: ["eco-friendly-plate-making", "baking-confectionery", "occupational-therapy"],
  },

  "computer-skills": {
    slug: "computer-skills", category: "Vocational Training", icon: "monitor", image: "what-we-offer.png",
    seoTitle: "Computer Skills & Digital Literacy for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "A supportive computer skills and digital literacy programme for special needs young adults in Chennai. Learn typing, data entry and online communication for greater independence and employability.",
    h1: "Computer Skills & Digital Literacy for Special Needs",
    lede: "A patient, step-by-step digital skills programme in Chennai that helps learners with special needs use computers confidently — opening doors to communication, learning and work.",
    intro: "Digital literacy is a gateway skill. Our computer programme introduces trainees aged 12 and above to the keyboard, mouse, files and the internet through clear, repeatable steps and plenty of one-to-one support. Learners build practical abilities — typing, data entry, email and safe online communication — that boost independence and make a real difference to employability.",
    age: "12 years and above", mode: "Vocational workshop · small-group & 1:1", duration: "Ongoing, with individual skill milestones",
    learnHeading: "What trainees learn",
    learn: ["Keyboard, mouse and basic computer operation", "Typing, document creation and data entry", "Email and safe online communication", "Using the internet responsibly", "Following digital tasks step by step"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) with intellectual disabilities, autism, learning disabilities or slow learning abilities who benefit from structured, screen-based learning at their own pace.",
    outcomesHeading: "Outcomes & certification",
    outcomes: ["Confident, independent use of a computer", "Practical data-entry and communication skills", "A foundation for digital and office-based work", "Pathway toward certification in digital literacy"],
    faq: [
      { q: "Does my child need to read fluently to start?", a: "No. We meet each learner at their level and adapt tasks, using visual cues and repetition to build skills gradually." },
      { q: "What software do trainees learn?", a: "Learners practise everyday tools — typing, documents, email and safe internet use — chosen to be practical and transferable." },
      { q: "Can this lead to work?", a: "Yes. Digital literacy supports many roles; our career counselling team helps match skills to suitable opportunities." },
      { q: "Is support one-to-one?", a: "Sessions blend small-group learning with one-to-one guidance, following each learner's personalised plan." },
    ],
    related: ["printing-merchandise", "nios-support", "life-skills-training"],
  },

  "printing-merchandise": {
    slug: "printing-merchandise", category: "Vocational Training", icon: "printer", image: "hero.png",
    seoTitle: "Printing & Merchandise Training for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "A practical printing and merchandise vocational programme for special needs young adults in Chennai. Learn print production and finishing skills that build independence and real employability.",
    h1: "Printing & Merchandise Training for Special Needs",
    lede: "A practical print-and-product workshop in Chennai where learners with special needs master print production and finishing — building a marketable, employable skill set.",
    intro: "Our printing and merchandise programme gives trainees aged 12 and above a real production routine: preparing designs, printing, and finishing merchandise to a sellable standard. The structured, step-by-step nature of print work suits many learners well, building sequencing, quality awareness and pride in a finished product they can hold in their hands.",
    age: "12 years and above", mode: "Vocational workshop · weekday programme", duration: "Ongoing, with individual skill milestones",
    learnHeading: "What trainees learn",
    learn: ["Preparing artwork and materials for printing", "Operating printing equipment safely", "Merchandise finishing and assembly", "Quality-checking and packaging products", "Following a production process end to end"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) who enjoy structured, hands-on production work — including those with intellectual disabilities, autism and slow learning abilities.",
    outcomesHeading: "Outcomes & certification",
    outcomes: ["A marketable print-production skill", "Strong sequencing and quality-awareness", "Pride and confidence from finished products", "Pathway toward certification in handicrafts"],
    faq: [
      { q: "What kind of products do trainees make?", a: "Learners work on printed merchandise — preparing, printing and finishing items to a sellable standard, with full supervision." },
      { q: "Is the equipment safe for my child?", a: "Yes. All equipment is operated under supervision, with tasks matched to each learner's ability and clear safety routines." },
      { q: "What age can my child start?", a: "The programme is open to learners aged 12 and above, following an initial assessment." },
      { q: "Does this help with employment?", a: "Print production is a transferable skill; our career counselling team supports the path toward suitable work." },
    ],
    related: ["computer-skills", "baking-confectionery", "housekeeping"],
  },

  "self-grooming-hygiene": {
    slug: "self-grooming-hygiene", category: "Vocational Training", icon: "sparkles", image: "whom-we-serve.png",
    seoTitle: "Self Grooming & Personal Hygiene Skills for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "A caring self-grooming and personal hygiene programme for special needs young adults in Chennai. Build daily-living routines for confidence, dignity and independence.",
    h1: "Self Grooming & Personal Hygiene Skills",
    lede: "A gentle daily-living programme in Chennai that helps learners with special needs build personal-care routines — the foundation of confidence, dignity and independence.",
    intro: "Personal care is the cornerstone of independent living. Our self-grooming and hygiene programme guides trainees aged 12 and above through everyday routines — washing, grooming, dressing and presentation — using clear steps, visual supports and patient encouragement. Mastering these skills builds self-esteem and prepares learners to take part more fully in vocational training and community life.",
    age: "12 years and above", mode: "Life-skills sessions · 1:1 and small group", duration: "Ongoing, with individual goals",
    learnHeading: "What learners practise",
    learn: ["Daily washing and personal hygiene routines", "Grooming, dressing and presentation", "Building consistent self-care habits", "Independence in everyday routines", "Confidence in personal and social settings"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) who are building independence in daily living — including those with intellectual disabilities, autism and Down syndrome who benefit from structured, supportive routine.",
    outcomesHeading: "Outcomes",
    outcomes: ["Independent personal-care routines", "Greater self-esteem and dignity", "Readiness for vocational and community participation", "Reduced reliance on caregivers for daily tasks"],
    faq: [
      { q: "Is this programme delivered sensitively?", a: "Yes. Personal care is taught with dignity, patience and privacy, using visual supports and gentle encouragement tailored to each learner." },
      { q: "Can it be combined with vocational training?", a: "Absolutely — self-care skills underpin every vocational programme and are often built into a learner's wider weekly plan." },
      { q: "Who delivers the sessions?", a: "Trained support staff deliver sessions one-to-one and in small groups, following each learner's personalised goals." },
      { q: "What age is it for?", a: "The programme supports learners aged 12 and above." },
    ],
    related: ["life-skills-training", "housekeeping", "occupational-therapy"],
  },

  "housekeeping": {
    slug: "housekeeping", category: "Vocational Training", icon: "house", image: "how-we-began.png",
    seoTitle: "Housekeeping & Facility Care Training for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "A practical housekeeping and facility-care vocational programme for special needs young adults in Chennai. Build organised, independent-living and employable cleaning skills.",
    h1: "Housekeeping & Facility Care Training",
    lede: "A practical housekeeping programme in Chennai where learners with special needs master facility-care routines — building order, independence and a genuinely employable skill.",
    intro: "Housekeeping teaches structure, responsibility and pride in a well-kept space. Trainees aged 12 and above learn cleaning, organising and facility-care routines through clear, repeatable steps. These skills support independent living at home and open the door to real roles in hospitality and facility services, with our team guiding the way.",
    age: "12 years and above", mode: "Vocational workshop · weekday programme", duration: "Ongoing, with individual skill milestones",
    learnHeading: "What trainees learn",
    learn: ["Cleaning and tidying routines, done safely", "Organising and maintaining spaces", "Using cleaning materials and tools correctly", "Following checklists and routines independently", "Care, responsibility and attention to detail"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) who do well with active, routine-based work — including those with intellectual disabilities, autism and slow learning abilities.",
    outcomesHeading: "Outcomes & certification",
    outcomes: ["Independent-living and facility-care skills", "A clear pathway to hospitality / facility roles", "Strong routines and responsibility", "Improved confidence and self-reliance"],
    faq: [
      { q: "What does the housekeeping programme cover?", a: "Learners practise real cleaning, organising and facility-care routines using safe, step-by-step methods and checklists." },
      { q: "Could this lead to a job?", a: "Yes — housekeeping skills are in demand in hospitality and facilities; our career counselling team supports the path to work." },
      { q: "Is it suitable for my child's needs?", a: "We assess each learner individually and adapt tasks and pacing to suit their abilities and goals." },
      { q: "Are cleaning products safe?", a: "All materials and tasks are supervised and matched to each learner's ability, with clear safety routines." },
    ],
    related: ["self-grooming-hygiene", "laundry-fabric-care", "life-skills-training"],
  },

  "eco-friendly-plate-making": {
    slug: "eco-friendly-plate-making", category: "Vocational Training", icon: "leaf", image: "what-we-offer.png",
    seoTitle: "Eco-Friendly Plate Making Training for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "A sustainable eco-friendly plate-making vocational programme for special needs young adults in Chennai. Learn biodegradable product making — a green, marketable, confidence-building skill.",
    h1: "Eco-Friendly Plate Making for Special Needs",
    lede: "A green, hands-on vocational programme in Chennai where learners with special needs make biodegradable plates from natural materials — a sustainable, marketable craft.",
    intro: "Making eco-friendly plates from natural materials is purposeful, repetitive and rewarding work. Trainees aged 12 and above learn to prepare materials, shape and press plates, and finish products to a sellable standard. The programme builds practical skill and environmental awareness, giving learners a real product — and a real sense of contribution — to be proud of.",
    age: "12 years and above", mode: "Vocational workshop · weekday programme", duration: "Ongoing, with individual skill milestones",
    learnHeading: "What trainees learn",
    learn: ["Preparing natural, biodegradable materials", "Shaping and pressing eco-friendly plates", "Finishing and quality-checking products", "Packaging and presenting items for sale", "Sustainability awareness and careful, consistent work"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) who enjoy hands-on, repetitive production — including those with intellectual disabilities, autism and slow learning abilities.",
    outcomesHeading: "Outcomes & certification",
    outcomes: ["A green, marketable production skill", "Environmental awareness and purpose", "Pride and confidence from finished products", "Pathway toward certification in handicrafts"],
    faq: [
      { q: "What materials are used?", a: "Plates are made from natural, biodegradable materials, supporting a sustainable, eco-friendly craft." },
      { q: "Is the work suitable for my child?", a: "The repetitive, hands-on nature suits many learners well; we tailor tasks and pacing to each individual." },
      { q: "Are the products sold?", a: "Trainees finish products to a sellable standard, which builds real-world skills and a sense of accomplishment." },
      { q: "What age can my child start?", a: "The programme is open to learners aged 12 and above." },
    ],
    related: ["gardening-horticulture", "baking-confectionery", "printing-merchandise"],
  },

  "laundry-fabric-care": {
    slug: "laundry-fabric-care", category: "Vocational Training", icon: "shirt", image: "whom-we-serve.png",
    seoTitle: "Laundry & Fabric Care Training for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "A practical laundry and fabric-care vocational programme for special needs young adults in Chennai. Learn washing, pressing and garment-care skills for independence and employability.",
    h1: "Laundry & Fabric Care Training",
    lede: "A structured laundry and garment-care programme in Chennai where learners with special needs master washing, pressing and fabric care — building independence and an employable skill.",
    intro: "Caring for clothes is an essential life skill and a real vocation. Trainees aged 12 and above learn to sort, wash, dry, press and fold garments through clear, repeatable routines. The step-by-step structure suits many learners well, building independence at home and opening the door to roles in laundry and hospitality services.",
    age: "12 years and above", mode: "Vocational workshop · weekday programme", duration: "Ongoing, with individual skill milestones",
    learnHeading: "What trainees learn",
    learn: ["Sorting, washing and drying garments", "Pressing, folding and finishing", "Caring for different fabrics safely", "Operating laundry equipment under supervision", "Following routines independently and carefully"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) who do well with routine, practical tasks — including those with intellectual disabilities, autism and slow learning abilities.",
    outcomesHeading: "Outcomes & certification",
    outcomes: ["Independent garment-care skills for home", "A pathway to laundry / hospitality roles", "Strong, repeatable routines", "Improved confidence and self-reliance"],
    faq: [
      { q: "What does the laundry programme teach?", a: "Learners practise sorting, washing, drying, pressing and folding, plus caring for different fabrics — all with supervision." },
      { q: "Is the equipment safe to use?", a: "Yes. Equipment is used under supervision, with tasks matched to each learner's ability and clear safety routines." },
      { q: "Can this lead to employment?", a: "Laundry and fabric-care skills are in demand in hospitality; our career counselling team supports the path to work." },
      { q: "What age is it for?", a: "The programme supports learners aged 12 and above." },
    ],
    related: ["housekeeping", "weaving", "self-grooming-hygiene"],
  },

  /* ============== EDUCATIONAL & THERAPEUTIC ============== */

  "nios-support": {
    slug: "nios-support", category: "Educational & Therapeutic", icon: "book-open", image: "what-we-offer.png",
    seoTitle: "NIOS Coaching for Special Needs Students — Chennai | Prisaum SEVA",
    metaDescription: "Supportive NIOS open-school coaching for special needs students in Chennai. Personalised, flexible academic support toward state certification, with care for learners with autism, LD and intellectual disabilities.",
    h1: "NIOS Coaching & Academic Support for Special Needs",
    lede: "Flexible, personalised NIOS open-school coaching in Chennai that helps special needs students work toward recognised state certification — at a pace that respects how they learn.",
    intro: "The National Institute of Open Schooling (NIOS) gives students who learn differently a flexible route to formal qualifications. At Prisaum SEVA, our educators provide patient, one-to-one academic support toward NIOS and state subjects — adapting materials, pacing and methods to each learner. We pair academics with life and social skills so that certification comes alongside genuine independence.",
    age: "12 years and above", mode: "Academic & therapeutic · scheduled weekly", duration: "Aligned to NIOS enrolment and exam cycles",
    learnHeading: "What students work on",
    learn: ["NIOS and state-subject coursework adapted to each learner", "Personalised pacing, materials and teaching methods", "Exam readiness and confidence-building", "Literacy, numeracy and study routines", "Life and social skills woven into academic sessions"],
    whoHeading: "Who this programme is for",
    who: "Students (12+) with autism, learning disabilities, intellectual disabilities or slow learning abilities who need a flexible, supportive route to certification rather than a conventional classroom.",
    outcomesHeading: "Outcomes & certification",
    outcomes: ["Progress toward recognised NIOS / state certification", "Stronger literacy, numeracy and study confidence", "An academic path that fits the learner, not the other way round", "Guidance for parents on next steps and career options"],
    faq: [
      { q: "What is NIOS and why does it suit special needs learners?", a: "NIOS is the National Institute of Open Schooling — a flexible, recognised board that allows adapted pacing and subject choice, making formal certification achievable for students who learn differently." },
      { q: "Do you adapt the material to my child's level?", a: "Yes. Every student works to a personalised plan, with materials, pacing and methods adapted to their needs and reviewed regularly." },
      { q: "Can NIOS support be combined with vocational training?", a: "Absolutely — many learners combine NIOS coaching with a vocational programme such as baking or weaving for a balanced week of academics and skills." },
      { q: "Do you support parents through the process?", a: "We guide parents through enrolment, expectations and next steps, and our career counselling team helps plan beyond certification." },
    ],
    related: ["computer-skills", "life-skills-training", "recreational-learning"],
  },

  "music-arts-therapy": {
    slug: "music-arts-therapy", category: "Educational & Therapeutic", icon: "music", image: "hero.png",
    seoTitle: "Music & Expressive Arts Therapy for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "Music and expressive arts therapy for special needs young adults in Chennai. Support emotional expression, regulation and joy through the arts, guided by professional artists.",
    h1: "Music & Expressive Arts Therapy",
    lede: "A joyful, therapeutic programme in Chennai where learners with special needs explore music and the arts — supporting expression, emotional regulation and connection.",
    intro: "The arts reach where words sometimes can't. Our music and expressive arts therapy invites learners aged 12 and above to sing, play, move and create alongside professional artists and trained staff. Sessions support emotional expression and regulation, build communication and social confidence, and — above all — bring joy, helping each learner feel seen and celebrated.",
    age: "12 years and above", mode: "Therapeutic sessions · group & 1:1", duration: "Ongoing, scheduled weekly",
    learnHeading: "What sessions support",
    learn: ["Emotional expression through music and art", "Self-regulation and calm", "Communication and turn-taking", "Social confidence in group settings", "Creativity, play and joy"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) of all abilities — including those with autism, intellectual disabilities and mental-health conditions — who benefit from expressive, sensory and social engagement.",
    outcomesHeading: "Outcomes",
    outcomes: ["Healthier emotional expression and regulation", "Stronger communication and social skills", "Increased confidence and engagement", "Genuine joy and a sense of belonging"],
    faq: [
      { q: "Does my child need musical or artistic talent?", a: "Not at all. Sessions are about expression and connection, not performance — every learner takes part at their own level." },
      { q: "Who leads the sessions?", a: "Professional artists work alongside our trained support staff to guide safe, supportive and joyful sessions." },
      { q: "Is it group or one-to-one?", a: "Both — we blend group sessions for social skills with one-to-one support where it helps." },
      { q: "Can it help with emotional regulation?", a: "Yes. Music and the arts are powerful tools for self-regulation, and sessions are designed with that in mind." },
    ],
    related: ["play-therapy", "recreational-learning", "occupational-therapy"],
  },

  "play-therapy": {
    slug: "play-therapy", category: "Educational & Therapeutic", icon: "blocks", image: "how-we-began.png",
    seoTitle: "Play Therapy for Special Needs Children — Chennai | Prisaum SEVA",
    metaDescription: "Structured play therapy for special needs children and young adults in Chennai. Build social confidence, communication and emotional skills through guided, playful sessions.",
    h1: "Play Therapy for Special Needs",
    lede: "A warm, structured play-therapy programme in Chennai where learners with special needs build social confidence, communication and emotional skills — through the natural language of play.",
    intro: "Play is how we learn to connect. Our structured play-therapy sessions give learners aged 12 and above a safe, guided space to explore, take turns, solve problems and express feelings. Led by trained staff, the playful format gently builds social and emotional skills, reduces anxiety and helps each learner engage more confidently with others.",
    age: "12 years and above", mode: "Therapeutic sessions · group & 1:1", duration: "Ongoing, scheduled weekly",
    learnHeading: "What sessions support",
    learn: ["Social interaction and turn-taking", "Communication and self-expression", "Emotional understanding and regulation", "Problem-solving through guided play", "Confidence and reduced anxiety"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) who build skills best through play and interaction — including those with autism, intellectual disabilities and mental-health conditions.",
    outcomesHeading: "Outcomes",
    outcomes: ["Stronger social and communication skills", "Better emotional understanding and regulation", "Increased confidence in group settings", "A safe space to express and grow"],
    faq: [
      { q: "Isn't play therapy just for young children?", a: "Structured play is a powerful, dignity-respecting tool across ages; we adapt activities to suit each learner aged 12 and above." },
      { q: "What happens in a session?", a: "Trained staff guide playful, structured activities that build social, communication and emotional skills in a safe space." },
      { q: "Is it one-to-one or group?", a: "We use both, blending group play for social skills with one-to-one support as needed." },
      { q: "How does it help my child?", a: "Play reduces anxiety and opens up communication, helping learners connect and build confidence over time." },
    ],
    related: ["music-arts-therapy", "recreational-learning", "life-skills-training"],
  },

  "recreational-learning": {
    slug: "recreational-learning", category: "Educational & Therapeutic", icon: "smile", image: "whom-we-serve.png",
    seoTitle: "Recreational Learning for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "Joyful, learner-led recreational learning for special needs young adults in Chennai. Build social skills, engagement and well-being through group activities and play.",
    h1: "Recreational Learning for Special Needs",
    lede: "A joyful, learner-led programme in Chennai where group activities and play build social skills, engagement and well-being for learners with special needs.",
    intro: "Learning is at its best when it's fun. Our recreational learning sessions bring learners aged 12 and above together for games, group activities and shared experiences that build friendships and social confidence. Light-hearted by design, the programme strengthens communication, cooperation and a sense of belonging — and gives every learner room to simply enjoy themselves.",
    age: "12 years and above", mode: "Group sessions · learner-led", duration: "Ongoing, scheduled weekly",
    learnHeading: "What sessions support",
    learn: ["Social interaction and friendship", "Cooperation and group participation", "Communication in relaxed settings", "Engagement, motivation and well-being", "Confidence and a sense of belonging"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) of all abilities who benefit from social, group-based engagement — including those with autism, intellectual disabilities and slow learning abilities.",
    outcomesHeading: "Outcomes",
    outcomes: ["Stronger friendships and social skills", "Greater engagement and motivation", "Improved communication and cooperation", "Happier, more connected learners"],
    faq: [
      { q: "What kind of activities are included?", a: "Sessions feature games, group activities and shared experiences chosen to be inclusive, fun and confidence-building." },
      { q: "Is it structured or free?", a: "It's learner-led but gently structured, so every participant can take part comfortably and meaningfully." },
      { q: "How does it help development?", a: "Recreation builds social skills, communication and well-being in a low-pressure, joyful setting." },
      { q: "What age is it for?", a: "The programme supports learners aged 12 and above." },
    ],
    related: ["play-therapy", "music-arts-therapy", "life-skills-training"],
  },

  "occupational-therapy": {
    slug: "occupational-therapy", category: "Educational & Therapeutic", icon: "activity", image: "what-we-offer.png",
    seoTitle: "Occupational Therapy for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "Occupational therapy for special needs young adults in Chennai. Build everyday-living skills, motor coordination and independence with personalised, professional support.",
    h1: "Occupational Therapy for Special Needs",
    lede: "Personalised occupational therapy in Chennai that helps learners with special needs build the everyday skills — motor, sensory and practical — that make independence possible.",
    intro: "Occupational therapy focuses on the skills people need for daily life. Our allied-health team works with learners aged 12 and above on motor coordination, sensory processing and practical everyday tasks, setting individual goals and adapting activities to each person. The result is steady, meaningful progress toward greater independence and well-being.",
    age: "12 years and above", mode: "Therapeutic sessions · 1:1, personalised", duration: "Ongoing, goal-reviewed regularly",
    learnHeading: "What therapy supports",
    learn: ["Fine and gross motor coordination", "Sensory processing and regulation", "Everyday practical and self-help tasks", "Individual goal-setting and progress", "Building independence step by step"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) who benefit from targeted skill-building — including those with autism, intellectual disabilities, Down syndrome and developmental needs.",
    outcomesHeading: "Outcomes",
    outcomes: ["Improved motor and sensory skills", "Greater independence in daily tasks", "Personalised, measurable progress", "Better participation in vocational and community life"],
    faq: [
      { q: "Who provides the occupational therapy?", a: "Sessions are delivered by our allied-health team, with personalised goals and regular review of progress." },
      { q: "How is the therapy tailored?", a: "Each learner has individual goals, and activities are adapted to their motor, sensory and practical needs." },
      { q: "Can it be combined with other programmes?", a: "Yes — occupational therapy often complements vocational and life-skills programmes within a learner's weekly plan." },
      { q: "What age is it for?", a: "The programme supports learners aged 12 and above." },
    ],
    related: ["life-skills-training", "self-grooming-hygiene", "music-arts-therapy"],
  },

  "life-skills-training": {
    slug: "life-skills-training", category: "Educational & Therapeutic", icon: "heart-handshake", image: "hero.png",
    seoTitle: "Life Skills Training for Special Needs — Chennai | Prisaum SEVA",
    metaDescription: "Life skills training for special needs young adults in Chennai. Build social, communication and self-help skills for confident, independent everyday living.",
    h1: "Life Skills Training for Special Needs",
    lede: "A practical life-skills programme in Chennai that helps learners with special needs build the social, communication and self-help abilities for confident, independent living.",
    intro: "Life skills tie everything together. Our programme helps learners aged 12 and above develop the social, communication and self-help abilities they use every day — from managing routines and money basics to interacting with others and solving everyday problems. Woven through all our training, life skills give each learner the confidence to participate more fully at home, at work and in the community.",
    age: "12 years and above", mode: "Life-skills sessions · group & 1:1", duration: "Ongoing, with individual goals",
    learnHeading: "What learners build",
    learn: ["Social and communication skills", "Self-help and daily-living routines", "Everyday problem-solving and decision-making", "Money and time basics", "Confidence and independence in the community"],
    whoHeading: "Who this programme is for",
    who: "Learners (12+) working toward greater independence — including those with intellectual disabilities, autism, Down syndrome and learning disabilities.",
    outcomesHeading: "Outcomes",
    outcomes: ["Confident, independent daily living", "Stronger social and communication skills", "Better problem-solving and self-reliance", "Fuller participation at home, work and community"],
    faq: [
      { q: "What does life skills training cover?", a: "It builds social, communication and self-help skills — routines, everyday problem-solving, money and time basics, and community participation." },
      { q: "Is it a standalone programme?", a: "It can be standalone, but life skills are also woven through our vocational and therapeutic programmes." },
      { q: "How is progress supported?", a: "Each learner works to individual goals with group and one-to-one support, reviewed regularly." },
      { q: "What age is it for?", a: "The programme supports learners aged 12 and above." },
    ],
    related: ["self-grooming-hygiene", "occupational-therapy", "nios-support"],
  },
};

window.PROGRAM_CONTENT = PROGRAM_CONTENT;
